source "http://rubygems.org"

gem "colored"
gem "chunky_png"

group :test do
  gem "cucumber", "0.10.7"
  gem "aruba",    "0.14.14"
  gem "rspec", "2.6.0"
  gem "capybara", "3.35.3"
  gem "capybara-webkit", "1.15.1"
end
