source "http://rubygems.org"

gem "colored"
gem "chunky_png"

group :test do
  gem "cucumber", "7.0.0"
  gem "aruba",    "0.14.14"
  gem "rspec", "2.99.0"
  gem "capybara", "3.35.3"
  gem "capybara-webkit", "0.14.2"
end
